"""first migration

Revision ID: 07e2775fd0c0
Revises:
Create Date: 2026-01-07 23:41:38.404828

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "07e2775fd0c0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("api_key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_merchants_email"), "merchants", ["email"], unique=True)
    op.create_index(op.f("ix_merchants_id"), "merchants", ["id"], unique=True)
    op.create_table(
        "payment_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_intents_id"), "payment_intents", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_payment_intents_merchant_id"),
        "payment_intents",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_intents_reference"),
        "payment_intents",
        ["reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_intents_status"), "payment_intents", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_intents_status"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_reference"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_merchant_id"), table_name="payment_intents")
    op.drop_index(op.f("ix_payment_intents_id"), table_name="payment_intents")
    op.drop_table("payment_intents")
    op.drop_index(op.f("ix_merchants_id"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_email"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
