"""added role column to merchant

Revision ID: 2f3aff372599
Revises: 07e2775fd0c0
Create Date: 2026-01-08 15:19:21.148259

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2f3aff372599"
down_revision: Union[str, Sequence[str], None] = "07e2775fd0c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "api_keys", ["id"])
    op.add_column(
        "merchants",
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("merchants", "role")
    op.drop_constraint(None, "api_keys", type_="unique")
    # ### end Alembic commands ###
