"""fixing db

Revision ID: ad7a3b351b92
Revises: 65ff5cd130e6
Create Date: 2026-01-15 15:55:38.572183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7a3b351b92'
down_revision: Union[str, Sequence[str], None] = '65ff5cd130e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_keys', 'merchants', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payment_intents', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_intents', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # ### end Alembic commands ###
